---
framework: jest
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/lint-verify-fail.test.js"
postMerge:
  pattern:
    - "./test/lint-verify-fail.test.js"
postRun:
     command:
        - node --version
version: 1.0
